# Generated by Django 4.2.16 on 2025-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
